services:
  webhook:
    image: syno-webhooks
    container_name: webhooks
    build:
      context: .
      args:
        PUID: 1026
        PGID: 100
        USER: ryan
    volumes:
      - /volume1/video:/data
      - /volume1/docker/syno_webhook/.env:/app/.env
    restart: no
    environment:
      PUID: 1026
      PGID: 100
      DEST_PATH: /data
    ports:
      - 5111:5111
